# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

vars:
  GITHUB: 'false'

tasks:
  setup:
    desc: Setup the project
    cmds:
      - rm -fr new-dir
      - |
        if [ "{{.GITHUB}}" = "true" ]; then
          uvx cookiecutter gh:gael-close/quarto-tech-paper --no-input
        else
          uvx cookiecutter . --no-input
        fi
      - defer: rm -rf venv # Optional: clean up if the sync fails halfway
      - cd new-dir && uv sync --extra dev
  basic-test:
    desc: Basic test
    cmds:
      - uv run pytest -s
    dir: new-dir
 
  
  render-all:
    desc: Render all supplementary materials and the paper
    cmds:
    - |
      task notebook NOTEBOOK=01-notebook.ipynb HTML=true
      task notebook NOTEBOOK=02-notebook.py HTML=true
      task render
      if [ ! -f "supplementary/01-notebook.html" ] || [ ! -f "supplementary/02-notebook.html" ]; then
        echo "Error: HTML files were not created in new-dir/supplementary!"
        exit 1
      fi

      task dist
    dir: new-dir

  view:
    desc: View all generated files (paper PDF and supplementary HTML)
    cmds: 
      - open manuscript/manuscript.pdf
      - open supplementary/01-notebook.html
      - open supplementary/02-notebook.html
    dir: new-dir
  
  save-example:
    desc: Distribute the landing page as an example (with Quarto site sidebar)
    cmds:
      - |
        # Create dist folder from the rendered site
        rm -fr dist
        cp -Lr new-dir/dist dist
      
        # Generate thumbnail
        (cd dist && magick -density 150 manuscript.pdf -quality 90 -background white -alpha remove thumbnail.png)
  
  test-all:
    desc: Run all tests from scratch
    cmds:
    - task: setup
    - task: basic-test
    - task: render
    - task: view
  